### ISSUE TITLE
UUID generation documentation

### ISSUE THREAD

**Issue by izenn** [laurinius/sto-aso#8]
**Is your feature request related to a problem? Please describe.**
When adding ships via ships.csv (not in the data direcotry), i'd like to add UUID's as well, however, i'd like to know how to generate them so they will not collide with what might officially be generated

**Describe the solution you'd like**
Please share how you are generating UUID's (and when you re-generate UUID's do get the same one every time for a specific ship? -- kind of like a md5sum or hash of the ship name?)

**Comment by ghost** [comment]
laurinius appears to be using v4 UUIDs (13th character is always 4, 17th character is always between 8-B). These are completely random and structured so that a collision is *exceedingly* unlikely to happen if you keep generating them. If he were hashing, it would be a v3 or v5.

Since I've been maintaining my own `ships.csv` for a while for Intrinsical's version, I used the following Excel/LibreOffice snippet to generate as many v4 UUIDs as I needed in a fresh column, then copied and pasted the *values* (rather than the cell with equation) in the ID column. Finally, I deleted my generator column before saving.

```excel
=LOWER(CONCATENATE(DEC2HEX(RANDBETWEEN(0,POWER(16,8)),8),"-",DEC2HEX(RANDBETWEEN(0,POWER(16,4)),4),"-","4",DEC2HEX(RANDBETWEEN(0,POWER(16,3)),3),"-",DEC2HEX(RANDBETWEEN(8,11)),DEC2HEX(RANDBETWEEN(0,POWER(16,3)),3),"-",DEC2HEX(RANDBETWEEN(0,POWER(16,8)),8),DEC2HEX(RANDBETWEEN(0,POWER(16,4)),4)))
```

In the case of a deliberate collision, the resulting behavior seems to not be predictable. I created a new entry for the `Ar'Kif Tactical Carrier Warbird Retrofit` in `ships.csv` with the same UUID as the `Ar'Kif Tactical Carrier Warbird` (they're the same card, but it got renamed at some point), and the new name overrode the old one. In the case of creating an entry for `Legendary Kelvin Timeline Intel Battlecruiser (T6)` with the same UUID as `Legendary Kelvin Timeline Constitution Intel Battlecruiser (T6)` (again, the same card, but the latter was renamed to the former and I added the ship trait), the latter won. 

I'd prefer it if the user version of the entry won in a case like this, as the only way a collision would likely occur with v4 UUIDs is a deliberate act and would be clearly intentional.

**Comment by laurinius** [comment]
The IDs are not really deeply integrated, just when saving/loading the user configuration it maps the IDs to the ship names (the names are still used internally as identifier by the app when loaded). I'll look into if I can use the ID as identifier throughout the app, which I think would help with the user ships override.
The intend was to have a workaround that allows renaming of ships while keeping the user config valid (otherwise the ship would be silently dropped when it couldn't find it).

Also IDs are optional, if no ID is there, it will still work, and instead use the name for saving/loading.

**Comment by laurinius** [comment]
I changed the code that UUIDs are now used internally as well to identify ships. That also helps with the behavior of the user ships. There will be more details on the IDs and user ships in the readme once the new version is released.
Especially you can add user ships without an ID, and then if you want migrate by adding the ID later. I want to keep adding own ships as simple as possible.
